# Generated by Django 3.2.14 on 2023-01-30 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_alter_snippet_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='description'),
        ),
    ]
